---
- name: Install all updates and reboot as many times as needed
  hosts: all
  tasks:

    - name: Create Directory for Logs
      ansible.windows.win_file:
        path: c:\temp
        state: directory

    # Check if a reboot is required BEFORE starting updates
    - name: Check if a reboot is pending before running updates
      win_shell: |
        $rebootRequired = $false
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired") {
            $rebootRequired = $true
        }
        if (Test-Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending") {
            $rebootRequired = $true
        }
        Write-Output $rebootRequired
      register: pre_update_reboot_check

    - name: Debug Output - Reboot Required Before Updates?
      ansible.builtin.debug:
        var: pre_update_reboot_check.stdout

    # Reboot IMMEDIATELY if required before running updates
    - name: Reboot if required before patching
      ansible.windows.win_reboot:
      when: pre_update_reboot_check.stdout | bool

    - name: Wait for system to be online after reboot
      wait_for_connection:
        delay: 60
        timeout: 600
      when: pre_update_reboot_check.stdout | bool

    # Run Updates Until No More Are Found OR A Reboot Is Required
    - name: Start Windows Patching
      ansible.windows.win_updates:
        category_names: "*"
        reboot: no
        log_path: c:\temp\patching.txt
      register: update_result
      until: update_result.found_update_count == 0 or not update_result.reboot_required
      retries: 3   # Prevents infinite loop by limiting retries
      delay: 30

    - name: Check if a reboot is required after patching
      ansible.builtin.set_fact:
        needs_reboot: "{{ update_result.reboot_required }}"

    - name: Debug output of reboot requirement
      ansible.builtin.debug:
        var: needs_reboot

    - name: Get current hour
      win_shell: (Get-Date).Hour
      register: current_hour

    - name: Debug output of current hour
      debug:
        var: current_hour.stdout

    # Reboot if required (ONLY inside the maintenance window)
    - name: Reboot if required (only during maintenance window)
      ansible.windows.win_reboot:
      when: 
        - needs_reboot | bool
        - current_hour.stdout | int >= 2
        - current_hour.stdout | int < 22

    - name: Wait for system to be online after reboot
      wait_for_connection:
        delay: 60
        timeout: 600
      when: needs_reboot | bool

    # Run updates one last time after reboot (if needed)
    - name: Run Windows Patching Again After Reboot
      ansible.windows.win_updates:
        category_names: "*"
        reboot: no
        log_path: c:\temp\patching_after_reboot.txt
      register: post_reboot_update_result
      until: post_reboot_update_result.found_update_count == 0 or not post_reboot_update_result.reboot_required
      retries: 2  # Prevents infinite loop
      delay: 30

    - name: Reboot Again If Needed
      ansible.windows.win_reboot:
      when: post_reboot_update_result.reboot_required | bool
