---
- name: Install all updates and reboot as many times as needed
  hosts: all
  tasks:
  
    - name: Create Directory for Logs
      ansible.windows.win_file:
        path: c:\temp
        state: directory

    - name: Start Windows Patching
      ansible.windows.win_updates:
        category_names: "*"
        reboot: no
        log_path: c:\temp\patching.txt
      register: update_result
      until: update_result.found_update_count == 0 or update_result.reboot_required
      retries: 5
      delay: 30

    - name: Check if a reboot is required
      ansible.builtin.set_fact:
        needs_reboot: "{{ update_result.reboot_required }}"

    - name: Debug output of reboot requirement
      ansible.builtin.debug:
        var: needs_reboot

    - name: Get current hour
      win_shell: (Get-Date).Hour
      register: current_hour

    - name: Debug output of current hour
      debug:
        var: current_hour.stdout

    - name: Reboot if required (only during maintenance window)
      ansible.windows.win_reboot:
      when: 
        - needs_reboot | bool
        - current_hour.stdout | int >= 2
        - current_hour.stdout | int < 5

    - name: Wait for system to be online after reboot
      wait_for_connection:
        delay: 60
        timeout: 600
      when: needs_reboot | bool

    - name: Run Windows Patching Again After Reboot
      ansible.windows.win_updates:
        category_names: "*"
        reboot: no
        log_path: c:\temp\patching_after_reboot.txt
      register: post_reboot_update_result
      until: post_reboot_update_result.found_update_count == 0 or post_reboot_update_result.reboot_required
      retries: 5
      delay: 30

    - name: Reboot Again If Needed
      ansible.windows.win_reboot:
      when: post_reboot_update_result.reboot_required | bool
