---
- name: Install Windows Updates 
  hosts: all
  tasks:
    - name: Create log directory
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: Install Windows Updates (No Auto Reboot)
      ansible.windows.win_updates:
        category_names: "*"
        reboot: no  # Do NOT reboot automatically
        log_path: C:\temp\patching.txt
      register: update_result
      ignore_errors: true  # Prevent playbook failure if reboot is needed

    - name: Check if a reboot is required
      ansible.builtin.set_fact:
        reboot_needed: "{{ update_result.reboot_required | default(false) }}"

    - name: Write reboot status to a log file
      ansible.windows.win_shell: |
        echo "Reboot required: {{ reboot_needed }}" >> C:\temp\patching_status.log
      when: reboot_needed

    - name: Notify administrators if a reboot is required
      ansible.builtin.debug:
        msg: "🚨 Reboot required on {{ inventory_hostname }}! Check C:/temp/patching_status.log"
      when: reboot_needed

    - name: Manually trigger a reboot (Optional)
      ansible.windows.win_reboot:
        reboot_timeout: 1800  # 30 minutes
      when: reboot_needed and confirm_reboot | default(false)
